export const products = [
  {
    id: 1,
    namn: "Phở bò",
    beskrivning: "Nudelsoppa med nötkött, färska örter och lime",
    pris: 139,
    bild: "./img/phokött.jpg",
    kategori: "Soppor",
  },
  {
    id: 2,
    namn: "Phở gà",
    beskrivning: "Nudelsoppa med kyckling, vårlök och koriander",
    pris: 129,
    bild: "./img/phokyckling.jpg",
    kategori: "Soppor",
  },
  {
    id: 3,
    namn: "Bánh mì thịt",
    beskrivning: "Fransk baguette med fläsk, picklad morot, rädisa och chili",
    pris: 89,
    bild: "./img/baguettekött.jpg",
    kategori: "Mackor",
  },
  {
    id: 4,
    namn: "Bánh mì gà",
    beskrivning: "Fransk baguette med grillad kyckling, majonnäs och färska grönsaker",
    pris: 89,
    bild: "./img/baguettekyckling.jpg",
    kategori: "Mackor",
  },
  {
    id: 5,
    namn: "Gỏi cuốn",
    beskrivning: "Färsk vårrulle med räkor, risnudlar och mynta, serveras med fisksås",
    pris: 75,
    bild: "./img/vårrullar.jpg",
    kategori: "Förrätter",
  },
  {
    id: 6,
    namn: "Chả giò",
    beskrivning: "Friterade vårrullar med fläskfärs, ägg och grönsaker, serveras med fisksås",
    pris: 65,
    bild: "./img/friedrolls.jpg",
    kategori: "Förrätter",
  },
  {
    id: 7,
    namn: "Cơm tấm",
    beskrivning: "Grillad fläskkarré med bruten ris, ägg och fisksås",
    pris: 149,
    bild: "./img/riskött.jpg",
    kategori: "Risrätter",
  },
  {
    id: 8,
    namn: "Bún chả",
    beskrivning: "Grillat fläsk med risnudlar, örter och dippsås",
    pris: 145,
    bild: "./img/nudlarkött.jpg",
    kategori: "Nudelrätter",
  }
];